# Generated by Django 5.2.8 on 2025-11-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100, verbose_name='Имя пациента')),
                ('date', models.DateField(verbose_name='Дата измерения')),
                ('weight', models.FloatField(verbose_name='Вес (кг)')),
                ('blood_pressure', models.CharField(help_text='Формат: 120/80', max_length=7, verbose_name='Артериальное давление')),
                ('pulse', models.IntegerField(verbose_name='Пульс (уд/мин)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Запись о здоровье',
                'verbose_name_plural': 'Записи о здоровье',
                'ordering': ['-date'],
            },
        ),
    ]
